name: pytest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install alpscore
        run: |
          sudo apt-get install wget
          wget https://sf.net/projects/materiappslive/files/Debian/sources/setup.sh
          sudo sh setup.sh
          sudo apt -y install mpi-default-dev libboost-all-dev libhdf5-dev libalpscore-dev
      - name: upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: install
        run: |
          pip install .[dev]
      - name: ruff
        run: |
          ruff check
      - name: pytest
        run: |
          pytest
      - name: ctest
        run: |
          cd build && ctest -V
